/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SocialLink = {
	_type: 'socialLink';
	icon?:
		| 'facebook'
		| 'instagram'
		| 'linkedin'
		| 'x'
		| 'youTube'
		| 'github'
		| 'spotify';
	url?: string;
};

export type SettingsBrandColorsReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'settingsBrandColors';
};

export type SectionAppearance = {
	_type: 'sectionAppearance';
	textAlign?: 'text-left' | 'text-center' | 'text-right' | 'text-justify';
	maxWidth?: 'none' | 'xl' | 'l' | 'm' | 's' | 'xs';
	spacingTop?:
		| 0
		| 1
		| 2
		| 3
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 14
		| 16
		| 20
		| 24
		| 28
		| 32
		| 36
		| 40
		| 44
		| 48
		| 52
		| 56
		| 60
		| 64
		| 72
		| 80
		| 96;
	spacingTopDesktop?:
		| 0
		| 1
		| 2
		| 3
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 14
		| 16
		| 20
		| 24
		| 28
		| 32
		| 36
		| 40
		| 44
		| 48
		| 52
		| 56
		| 60
		| 64
		| 72
		| 80
		| 96;
	spacingBottom?:
		| 0
		| 1
		| 2
		| 3
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 14
		| 16
		| 20
		| 24
		| 28
		| 32
		| 36
		| 40
		| 44
		| 48
		| 52
		| 56
		| 60
		| 64
		| 72
		| 80
		| 96;
	spacingBottomDesktop?:
		| 0
		| 1
		| 2
		| 3
		| 4
		| 5
		| 6
		| 7
		| 8
		| 9
		| 10
		| 11
		| 12
		| 14
		| 16
		| 20
		| 24
		| 28
		| 32
		| 36
		| 40
		| 44
		| 48
		| 52
		| 56
		| 60
		| 64
		| 72
		| 80
		| 96;
	backgroundColor?: SettingsBrandColorsReference;
	textColor?: SettingsBrandColorsReference;
};

export type PortableTextSimple = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: Array<
		{
			_key: string;
		} & Link
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type PortableText = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?:
				| 'normal'
				| 'h1'
				| 'h2'
				| 'h3'
				| 'h4'
				| 'h5'
				| 'h6'
				| 'label'
				| 'blockquote';
			listItem?: 'bullet' | 'number';
			markDefs?: Array<
				| ({
						_key: string;
				  } & Link)
				| {
						link?: Link;
						_type: 'callToAction';
						_key: string;
				  }
			>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			link?: Link;
			_type: 'image';
			_key: string;
	  }
	| {
			embedSnippet?: string;
			_type: 'iframe';
			_key: string;
	  }
>;

export type NavItem = {
	_type: 'navItem';
	title?: string;
	link?: Link;
};

export type NavDropdown = {
	_type: 'navDropdown';
	title?: string;
	dropdownItems?: Array<
		{
			_key: string;
		} & NavItem
	>;
};

export type PHomeReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'pHome';
};

export type LinkInput = {
	_type: 'linkInput';
	linkType?: 'internal' | 'external';
	internalLink?: PHomeReference;
	externalUrl?: string;
};

export type Link = {
	_type: 'link';
	linkInput?: LinkInput;
	isNewTab?: boolean;
};

export type FormFields = {
	_type: 'formFields';
	required?: boolean;
	fieldLabel?: string;
	inputType?:
		| 'text'
		| 'email'
		| 'tel'
		| 'textarea'
		| 'select'
		| 'checkbox'
		| 'file';
	placeholder?: string;
	selectOptions?: Array<{
		option?: string;
		_key: string;
	}>;
};

export type Freeform = {
	_type: 'freeform';
	content?: PortableText;
	sectionAppearance?: SectionAppearance;
};

export type PContact = {
	_id: string;
	_type: 'pContact';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	contactForm?: {
		formTitle?: string;
		formFields?: Array<
			{
				_key: string;
			} & FormFields
		>;
		successMessage?: string;
		errorMessage?: string;
		sendToEmail?: string;
		emailSubject?: string;
		formFailureNotificationEmail?: string;
	};
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type PEventStatus = {
	_id: string;
	_type: 'pEventStatus';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	statusColor?: SettingsBrandColorsReference;
};

export type PEvents = {
	_id: string;
	_type: 'pEvents';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type PEventCategory = {
	_id: string;
	_type: 'pEventCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	categoryColor?: SettingsBrandColorsReference;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type PEventCategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'pEventCategory';
};

export type PEventStatusReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'pEventStatus';
};

export type PEvent = {
	_id: string;
	_type: 'pEvent';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	subtitle?: string;
	slug?: Slug;
	eventDatetime?: string;
	location?: string;
	locationLink?: string;
	categories?: Array<
		{
			_key: string;
		} & PEventCategoryReference
	>;
	status?: Array<
		{
			_key: string;
		} & PEventStatusReference
	>;
	content?: PortableText;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type PBlogCategory = {
	_id: string;
	_type: 'pBlogCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	categoryColor?: SettingsBrandColorsReference;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type GAuthorReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'gAuthor';
};

export type PBlogCategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'pBlogCategory';
};

export type PBlogReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'pBlog';
};

export type PBlog = {
	_id: string;
	_type: 'pBlog';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	author?: GAuthorReference;
	categories?: Array<
		{
			_key: string;
		} & PBlogCategoryReference
	>;
	excerpt?: string;
	content?: PortableText;
	relatedBlogs?: Array<
		{
			_key: string;
		} & PBlogReference
	>;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type GAuthor = {
	_id: string;
	_type: 'gAuthor';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
};

export type PBlogIndex = {
	_id: string;
	_type: 'pBlogIndex';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	itemsPerPage?: number;
	paginationMethod?: 'page-numbers' | 'load-more' | 'infinite-scroll';
	loadMoreButtonLabel?: string;
	infiniteScrollCompleteLabel?: string;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type PHome = {
	_id: string;
	_type: 'pHome';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	landingTitle?: string;
	textColor?: SettingsBrandColorsReference;
	pageModules?: Array<
		{
			_key: string;
		} & Freeform
	>;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type P404 = {
	_id: string;
	_type: 'p404';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	heading?: string;
	paragraph?: PortableTextSimple;
	callToAction?: {
		label?: string;
		link?: Link;
	};
};

export type PGeneral = {
	_id: string;
	_type: 'pGeneral';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	content?: PortableText;
	sharing?: {
		disableIndex?: boolean;
		metaTitle?: string;
		metaDesc?: string;
		shareGraphic?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
};

export type SettingsMenuReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'settingsMenu';
};

export type GFooter = {
	_id: string;
	_type: 'gFooter';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	menu?: SettingsMenuReference;
	menuLegal?: SettingsMenuReference;
	toolbarMenu?: SettingsMenuReference;
	note?: string;
};

export type GHeader = {
	_id: string;
	_type: 'gHeader';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	menu?: SettingsMenuReference;
};

export type GAnnouncement = {
	_id: string;
	_type: 'gAnnouncement';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	display?: 'hidden' | 'all' | 'homepage';
	messages?: Array<{
		content?: PortableTextSimple;
		_key: string;
	}>;
	autoplay?: boolean;
	autoplayInterval?: number;
	backgroundColor?: Color;
	textColor?: Color;
	emphasizeColor?: Color;
};

export type Color = {
	_type: 'color';
	hex?: string;
	alpha?: number;
	hsl?: HslaColor;
	hsv?: HsvaColor;
	rgb?: RgbaColor;
};

export type SettingsIntegration = {
	_id: string;
	_type: 'settingsIntegration';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	gaIDs?: Array<string>;
	gtmIDs?: Array<string>;
};

export type SettingsRedirect = {
	_id: string;
	_type: 'settingsRedirect';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	url?: Slug;
	destination?: LinkInput;
	permanent?: boolean;
};

export type SettingsMenu = {
	_id: string;
	_type: 'settingsMenu';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	items?: Array<
		| ({
				_key: string;
		  } & NavItem)
		| ({
				_key: string;
		  } & NavDropdown)
	>;
};

export type SettingsBrandColors = {
	_id: string;
	_type: 'settingsBrandColors';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	color?: Color;
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type SettingsGeneral = {
	_id: string;
	_type: 'settingsGeneral';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	siteTitle?: string;
	siteDesc?: Note;
	shareGraphic?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	shareVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	favicon?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	faviconLight?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Note = string;

export type RgbaColor = {
	_type: 'rgbaColor';
	r?: number;
	g?: number;
	b?: number;
	a?: number;
};

export type HsvaColor = {
	_type: 'hsvaColor';
	h?: number;
	s?: number;
	v?: number;
	a?: number;
};

export type HslaColor = {
	_type: 'hslaColor';
	h?: number;
	s?: number;
	l?: number;
	a?: number;
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SocialLink
	| SettingsBrandColorsReference
	| SectionAppearance
	| PortableTextSimple
	| SanityImageAssetReference
	| PortableText
	| NavItem
	| NavDropdown
	| PHomeReference
	| LinkInput
	| Link
	| FormFields
	| Freeform
	| PContact
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| PEventStatus
	| PEvents
	| PEventCategory
	| PEventCategoryReference
	| PEventStatusReference
	| PEvent
	| PBlogCategory
	| GAuthorReference
	| PBlogCategoryReference
	| PBlogReference
	| PBlog
	| GAuthor
	| PBlogIndex
	| PHome
	| P404
	| PGeneral
	| SettingsMenuReference
	| GFooter
	| GHeader
	| GAnnouncement
	| Color
	| SettingsIntegration
	| SettingsRedirect
	| SettingsMenu
	| SettingsBrandColors
	| SanityFileAssetReference
	| SettingsGeneral
	| Note
	| RgbaColor
	| HsvaColor
	| HslaColor
	| MediaTag
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
